#
# Makefile: Commands to simplify development and releases
#
# Usage:
#
#    make clean
#    make tests

# This Makefile only works with GNU Make.

PYTHON = python3.12

# Where everything lives
site_python := /usr/bin/env $(PYTHON)

root_dir := $(realpath .)

venv_name = .venv
venv_dir = $(root_dir)/$(venv_name)
python = $(venv_dir)/bin/python
gunicorn = $(venv_dir)/bin/gunicorn

pytest = $(python) -m pytest
coverage = $(python) -m coverage

# include additional targets or override variables from local makefiles
-include *.mk

.PHONY: help
help:
	@echo "The Makefile has the following targets..."
	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | grep -E -v -e '^[^[:alnum:]]' -e '^$@$$'

# #########
#   Clean
# #########
#
# Delete all the runtime files generated by the various targets.
# Note: there is no target for cleaning the virtualenv as there is no
# universal way of deactivate it before deleting the files. Each tool,
# virtualenvwrapper, pyenv, etc. uses different mechanism. In any case
# doing this within a Makefile is not possible, since a separate shell
# is spawned for each command, so the current one is unaffected.

.PHONY: clean-tests
clean-tests:
	@echo "Deleting the pytest cache..."
	rm -rf .pytest_cache

.PHONY: clean-mypy
clean-mypy:
	@echo "Deleting the mypy cache..."
	rm -rf .mypy_cache

.PHONY: clean-coverage
clean-coverage:
	@echo "Deleting the coverage data and reports..."
	rm -rf .coverage
	rm -rf coverage

.PHONY: clean
clean: clean-coverage clean-mypy clean-tests

# ##########
#   Django
# ##########

.PHONY: migrate
migrate:
	@echo "Run any database migrations..."
	$(python) manage.py migrate

.PHONY: run
run: migrate
	@echo "Run Gunicorn web server..."
	$(gunicorn) -c main/gunicorn.py main.wsgi

# #########
#   Tests
# #########

.PHONY: coverage
coverage:
	@echo "Generate test coverage report..."
	$(pytest) --cov=$(src_dir) --cov-report html

.PHONY: tests
tests:
	@echo "Run all the tests..."
	$(pytest)
