# Generated by Django 5.2.4 on 2025-07-21 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverSpeciesLatest',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('name', models.TextField(help_text='The name of the observer.', verbose_name='name')),
            ],
            options={
                'verbose_name': 'ObserverSpeciesLatest',
                'verbose_name_plural': 'ObserverSpeciesLatest',
                'db_table': 'observer_species_latest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObserverSpeciesMonthly',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('name', models.TextField(help_text='The name of the observer.', verbose_name='name')),
                ('year', models.IntegerField(db_index=True, help_text='The year the observation was made.', verbose_name='year')),
                ('month', models.IntegerField(db_index=True, help_text='The month the observation was made.', verbose_name='month')),
            ],
            options={
                'verbose_name': 'ObserverSpeciesMonthly',
                'verbose_name_plural': 'ObserverSpeciesMonthly',
                'db_table': 'observer_species_monthly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObserverSpeciesWeekly',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('name', models.TextField(help_text='The name of the observer.', verbose_name='name')),
                ('year', models.IntegerField(db_index=True, help_text='The year the observation was made.', verbose_name='year')),
                ('week', models.IntegerField(db_index=True, help_text='The week the observation was made.', verbose_name='week')),
            ],
            options={
                'verbose_name': 'ObserverSpeciesWeekly',
                'verbose_name_plural': 'ObserverSpeciesWeekly',
                'db_table': 'observer_species_weekly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearList',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('date', models.DateField(db_index=True, help_text='The date the observation was made.', verbose_name='date')),
                ('count', models.IntegerField(help_text='The number of birds seen.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='count')),
                ('approved', models.BooleanField(default=True, help_text='Has the observation been accepted.', verbose_name='Approved')),
                ('reason', models.TextField(blank=True, help_text='The reason given for the observation to be marked as not approved.', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'YearList',
                'verbose_name_plural': 'YearLists',
                'db_table': 'year_list',
                'managed': False,
            },
        ),
    ]
