# Generated by Django 5.2.4 on 2025-08-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_materialized_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearList',
        ),
        migrations.RunSQL(
            sql="DROP MATERIALIZED VIEW year_list",
        ),
    ]
