# Generated by Django 5.2.4 on 2025-07-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_materialized_views'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP MATERIALIZED VIEW year_list",
        ),
        migrations.RunSQL(
            sql="CREATE MATERIALIZED VIEW year_list AS "
                "SELECT DISTINCT ON (species_id, country_id, state_id, county_id, year) "
                "identifier, checklist_id, species_id, observer_id, country_id, state_id, county_id, location_id, date, count, approved, reason "
                "EXTRACT (YEAR FROM date) AS year, "
                "FROM data_observation "
                "INNER JOIN data_species ON species_id = data_species.species_code "
                "WHERE data_species.category = 'species' AND published = true "
                "ORDER BY species_id, country_id, state_id, county_id, started",
        )
    ]
