# Generated by Django 5.1.4 on 2025-04-11 12:16

from django.db import migrations

def set_observation_time(apps, schema_editor):
    Observation = apps.get_model("checklists", "Observation")

    for observation in Observation.objects.all():
        observation.time = observation.checklist.time
        observation.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "checklists",
            "0005_observation_time",
        ),
    ]

    operations = [
        migrations.RunPython(set_observation_time),
    ]
