# Generated by Django 5.2.2 on 2025-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, help_text='The date the Update was published. May be in the future', null=True, verbose_name='Published')),
                ('title', models.CharField(help_text='The title of the Update', max_length=100, verbose_name='Title')),
                ('contents', models.TextField(help_text='The contents of the Update. HTML is allowed', verbose_name='Contents')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
