# Generated by Django 5.1.4 on 2025-04-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The code used to identify the county.",
                        max_length=10,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the county.", verbose_name="name"
                    ),
                ),
                (
                    "place",
                    models.TextField(
                        help_text="The hierarchical name of the county.",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "county",
                "verbose_name_plural": "counties",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The code used to identify the state.",
                        max_length=10,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the state.", verbose_name="name"
                    ),
                ),
                (
                    "place",
                    models.TextField(
                        help_text="The hierarchical name of the state.",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "state",
                "verbose_name_plural": "states",
            },
        ),
        migrations.AlterField(
            model_name="area",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="The code used to identify the area.",
                max_length=10,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="The region where the checklist was made.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checklists",
                to="data.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="The region for the location.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="data.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="The region where the observation was made.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="data.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="The code used to identify the region.",
                max_length=10,
                verbose_name="code",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="The county where the checklist was made.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklists",
                to="data.county",
                verbose_name="county",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="The county for the location.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="data.county",
                verbose_name="county",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="The county where the observation was made.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="data.county",
                verbose_name="county",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="The state where the checklist was made.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklists",
                to="data.state",
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="The state for the location.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="data.state",
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="The state where the observation was made.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="data.state",
                verbose_name="state",
            ),
        ),
    ]
