# Generated by Django 5.2.1 on 2025-05-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='multiple',
            field=models.BooleanField(default=False, help_text='Is the name used by more than one eBird account.', verbose_name='Multiple accounts'),
        ),
    ]
