# Generated by Django 5.2.1 on 2025-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_observer_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Load checklists from the eBird observer.', verbose_name='Enabled'),
        ),
    ]
