# Generated by Django 5.1.4 on 2025-04-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_set_district_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="byname",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The display name of the location",
                verbose_name="byname",
            ),
        ),
    ]
