# Generated by Django 5.2.1 on 2025-05-27 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_observer_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='count',
            field=models.IntegerField(default=0, help_text='The number of birds seen.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='count'),
            preserve_default=False,
        ),
    ]
