# Generated by Django 5.2.3 on 2025-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_observation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='approved',
            field=models.BooleanField(default=True, help_text='Has the observation been accepted.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='If the observation was not approved, has it been reviewed.', verbose_name='Reviewed'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='reason',
            field=models.TextField(blank=True, help_text='The reason given for the observation to be marked as not approved.', verbose_name='Reason'),
        ),
    ]
