# Generated by Django 5.1.4 on 2025-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_location_byname"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="The time the observation was made.",
                null=True,
                verbose_name="time",
            ),
        ),
    ]
