# Generated by Django 5.2.3 on 2025-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_observation_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='exotic_code',
        ),
        migrations.RemoveField(
            model_name='species',
            name='subspecies_common_name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='subspecies_scientific_name',
        ),
    ]
