# Generated by Django 5.2.3 on 2025-06-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_species_exotic_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='age_sex',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='behavior_code',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='breeding_category',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='breeding_code',
        ),
    ]
