# Generated by Django 5.2.3 on 2025-06-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_observation_age_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='protocol',
        ),
    ]
