# Generated by Django 5.1.4 on 2025-04-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_remove_unused_location_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="observer",
            name="byname",
            field=models.TextField(
                blank=True,
                help_text="The display name of the observer",
                verbose_name="byname",
            ),
        ),
    ]
