# Generated by Django 5.1.4 on 2025-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_observer_byname"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="started",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The date and time the observation was made.",
                null=True,
                verbose_name="date & time",
            ),
        ),
    ]
