# Generated by Django 5.2.3 on 2025-06-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_checklist_group_remove_checklist_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='coverage',
            new_name='area',
        ),
    ]
