# Generated by Django 5.1.4 on 2025-04-15 09:32

from django.db import migrations

def set_observation_started(apps, schema_editor):
    Observation = apps.get_model("data", "Observation")

    for observation in Observation.objects.all().select_related("checklist"):
        observation.started = observation.checklist.started
        observation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_observation_started"),
    ]

    operations = [
        migrations.RunPython(set_observation_started),
    ]
