# Generated by Django 5.2.3 on 2025-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_coverage_checklist_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='published',
            field=models.BooleanField(default=True, help_text='Is the checklist published?', verbose_name='published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='published',
            field=models.BooleanField(default=True, help_text='Is the observation published?', verbose_name='published'),
            preserve_default=False,
        ),
    ]
