# Generated by Django 5.1.4 on 2025-04-15 10:49
import requests
import socket

from bs4 import BeautifulSoup

from django.db import migrations

socket.setdefaulttimeout(30)

def set_observer_identifier(apps, schema_editor):
    Observer = apps.get_model("data", "Observer")

    for observer in Observer.objects.filter(identifier=""):
        for checklist in observer.checklists.all():
            try:
                response = requests.get(checklist.url)
                content = response.content
                soup = BeautifulSoup(content, "lxml")
                attribute = "data-participant-userid"
                node = soup.find("span", attrs={attribute: True})
                observer.identifier = node[attribute] if node else ""
                observer.save()
                break
            except:  # noqa
                pass

class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_set_observation_started"),
    ]

    operations = [
        migrations.RunPython(set_observer_identifier),
    ]
