# Generated by Django 5.2.3 on 2025-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='decision',
            field=models.TextField(blank=True, help_text='The decision given when the observation was reviewed.', verbose_name='Decision'),
        ),
    ]
