# Generated by Django 5.2.3 on 2025-06-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_observation_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the event occurred', verbose_name='created')),
                ('type', models.IntegerField(choices=[(1, 'Observation rejected'), (2, 'Observation reviewed')], help_text='The type of event that occurred.', verbose_name='type')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Data describing the Event.', verbose_name='Data')),
                ('observation', models.ForeignKey(help_text='The Observation associated with this event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data.observation', verbose_name='observation')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
