# Generated by Django 5.2.3 on 2025-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.TextField(blank=True, choices=[('', 'All categories'), ('species', 'Species'), ('issf', 'Subspecies'), ('domestic', 'Domestic'), ('hybrid', 'Hybrid')], help_text='The category from the eBird/Clements taxonomy.', verbose_name='category'),
        ),
    ]
