# Generated by Django 5.2.3 on 2025-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_species_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='media',
        ),
        migrations.AddField(
            model_name='observation',
            name='audio',
            field=models.BooleanField(default=False, help_text='Have audio recordings been uploaded to the Macaulay library.', verbose_name='has audio'),
        ),
        migrations.AddField(
            model_name='observation',
            name='photo',
            field=models.BooleanField(default=False, help_text='Have photos been uploaded to the Macaulay library.', verbose_name='has photos'),
        ),
        migrations.AddField(
            model_name='observation',
            name='video',
            field=models.BooleanField(default=False, help_text='Have video recordings been uploaded to the Macaulay library.', verbose_name='has video'),
        ),
    ]
