# Generated by Django 5.2.3 on 2025-06-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_add_fields_for_media_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location used to find matching Observations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtered_on', to='data.location', verbose_name='location'),
        ),
    ]
