# Generated by Django 5.2.3 on 2025-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_filter_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Observation rejected'), (2, 'Observation accepted')], help_text='The type of event that occurred.', verbose_name='type'),
        ),
    ]
