# Generated by Django 5.2.3 on 2025-07-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='reviewed',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
