# Generated by Django 5.2.3 on 2025-07-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_remove_observation_decision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='original',
        ),
        migrations.RenameField(
            model_name='observer',
            old_name='name',
            new_name='original',
        ),
    ]
