# Generated by Django 5.2.3 on 2025-07-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20250710_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='byname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='observer',
            old_name='byname',
            new_name='name',
        ),
    ]
