# Generated by Django 5.2.3 on 2025-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20250710_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='identifier',
            field=models.TextField(help_text='The unique identifier for the location.', unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(help_text='The display name of the location.', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='original',
            field=models.TextField(help_text='The original name of the location from eBird.', verbose_name='original name'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='name',
            field=models.TextField(help_text='The display name of the observer.', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='original',
            field=models.TextField(help_text='The original name of the observer from eBird.', verbose_name='original name'),
        ),
    ]
