# Generated by Django 5.2.4 on 2025-08-01 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('category', models.TextField(blank=True, choices=[('species', 'Species'), ('slash', 'Species pairs'), ('issf', 'Subspecies'), ('domestic', 'Domestic species'), ('hybrid', 'Hybrids'), ('form', 'Species forms'), ('spuh', 'Unidentified species'), ('intergrade', 'Intergrades')], help_text='The category from the eBird/Clements taxonomy.', verbose_name='category')),
                ('date', models.DateField(db_index=True, help_text='The date the observation was made.', verbose_name='date')),
                ('started', models.DateTimeField(blank=True, db_index=True, help_text='The date and time the observation was made.', null=True, verbose_name='date & time')),
                ('year', models.IntegerField(db_index=True, help_text='The year the observation was made.', verbose_name='year')),
                ('count', models.IntegerField(help_text='The number of birds seen.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='count')),
                ('approved', models.BooleanField(default=True, help_text='Has the observation been accepted.', verbose_name='Approved')),
                ('reason', models.TextField(blank=True, help_text='The reason given for the observation to be marked as not approved.', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Country List',
                'verbose_name_plural': 'Country Lists',
                'db_table': 'country_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountyList',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('category', models.TextField(blank=True, choices=[('species', 'Species'), ('slash', 'Species pairs'), ('issf', 'Subspecies'), ('domestic', 'Domestic species'), ('hybrid', 'Hybrids'), ('form', 'Species forms'), ('spuh', 'Unidentified species'), ('intergrade', 'Intergrades')], help_text='The category from the eBird/Clements taxonomy.', verbose_name='category')),
                ('date', models.DateField(db_index=True, help_text='The date the observation was made.', verbose_name='date')),
                ('started', models.DateTimeField(blank=True, db_index=True, help_text='The date and time the observation was made.', null=True, verbose_name='date & time')),
                ('year', models.IntegerField(db_index=True, help_text='The year the observation was made.', verbose_name='year')),
                ('count', models.IntegerField(help_text='The number of birds seen.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='count')),
                ('approved', models.BooleanField(default=True, help_text='Has the observation been accepted.', verbose_name='Approved')),
                ('reason', models.TextField(blank=True, help_text='The reason given for the observation to be marked as not approved.', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'County List',
                'verbose_name_plural': 'County Lists',
                'db_table': 'county_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateList',
            fields=[
                ('identifier', models.CharField(help_text='The unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier')),
                ('category', models.TextField(blank=True, choices=[('species', 'Species'), ('slash', 'Species pairs'), ('issf', 'Subspecies'), ('domestic', 'Domestic species'), ('hybrid', 'Hybrids'), ('form', 'Species forms'), ('spuh', 'Unidentified species'), ('intergrade', 'Intergrades')], help_text='The category from the eBird/Clements taxonomy.', verbose_name='category')),
                ('date', models.DateField(db_index=True, help_text='The date the observation was made.', verbose_name='date')),
                ('started', models.DateTimeField(blank=True, db_index=True, help_text='The date and time the observation was made.', null=True, verbose_name='date & time')),
                ('year', models.IntegerField(db_index=True, help_text='The year the observation was made.', verbose_name='year')),
                ('count', models.IntegerField(help_text='The number of birds seen.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='count')),
                ('approved', models.BooleanField(default=True, help_text='Has the observation been accepted.', verbose_name='Approved')),
                ('reason', models.TextField(blank=True, help_text='The reason given for the observation to be marked as not approved.', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'State List',
                'verbose_name_plural': 'State Lists',
                'db_table': 'state_list',
                'managed': False,
            },
        ),
    ]
