# Generated by Django 5.2.4 on 2025-07-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE MATERIALIZED VIEW country_list AS "
                "SELECT DISTINCT ON (species_id, country_id) "
                "identifier, checklist_id, species_id, data_species.category, observer_id, country_id, state_id, county_id, location_id, date, started, count, approved, reason, "
                "EXTRACT (YEAR FROM date) AS year "
                "FROM data_observation "
                "INNER JOIN data_species ON species_id = data_species.species_code "
                "ORDER BY species_id, country_id, started",
            reverse_sql="DROP MATERIALIZED VIEW country_list"
        ),
        migrations.RunSQL(
            sql="CREATE MATERIALIZED VIEW state_list AS "
                "SELECT DISTINCT ON (species_id, state_id) "
                "identifier, checklist_id, species_id, data_species.category, observer_id, country_id, state_id, county_id, location_id, date, started, count, approved, reason, "
                "EXTRACT (YEAR FROM date) AS year "
                "FROM data_observation "
                "INNER JOIN data_species ON species_id = data_species.species_code "
                "ORDER BY species_id, state_id, started",
            reverse_sql="DROP MATERIALIZED VIEW state_list"
        ),
        migrations.RunSQL(
            sql="CREATE MATERIALIZED VIEW county_list AS "
                "SELECT DISTINCT ON (species_id, county_id) "
                "identifier, checklist_id, species_id, data_species.category, observer_id, country_id, state_id, county_id, location_id, date, started, count, approved, reason, "
                "EXTRACT (YEAR FROM date) AS year "
                "FROM data_observation "
                "INNER JOIN data_species ON species_id = data_species.species_code "
                "ORDER BY species_id, county_id, started",
            reverse_sql="DROP MATERIALIZED VIEW county_list"
        ),
    ]
