# Generated by Django 5.2.1 on 2025-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(blank=True, help_text='The date the Notification was published. May be in the future', null=True, verbose_name='Published')),
                ('expired', models.DateTimeField(blank=True, help_text='The date the Notification will expire and no longer be available', null=True, verbose_name='Expired')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], help_text='The alert level for the notification', max_length=20)),
                ('title', models.CharField(help_text='The title of the Notification', max_length=100, verbose_name='Title')),
                ('contents', models.TextField(help_text='The contents of the Notification', verbose_name='Contents')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Data describing a Notification.', verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
